export const funMessages = [
  "You expected something to happen? That's cute.",
  "This button just applied for sick leave. Try again later.",
  "This button is legally required to ignore you. Any further clicks will be considered harassment.",
  "This button doesn't work, but you do. Go touch some grass",
  "Hold on, the fest coordinators are still arguing over what this button does.",
  "This button was supposed to open something… then the committee forgot.",
  "Nice try! This was just a test to see if you'd fall for a pointless feature. You did.",
  "Nice try! This is just a test to see if you're paying attention.",
  "This button was last seen running away with the fest sponsorship money.",
  "Nope. Not today. This button is on a 'No Work' strike.",
  "Your click has been forwarded to the most clueless fest volunteer.",
  "This button just ghosted you like your fest crush.",
  "Your click just got added to the 8-hour-long registration queue.",
  "This button had dreams once. Then it joined the fest committee.",
  "Breaking news: Your click has been ignored just like our budget requests.",
  "Clicking this just added your name to the 'forever unpaid volunteers' list.",
  "You clicked? Nice. Now go enjoy the fest instead of pressing useless buttons.",
];
